import { AssessmentPath } from './types';

export const ASSESSMENT_PATHS: AssessmentPath[] = [
  {
    id: 'atleta',
    title: 'Recupero infortunio per atleta',
    description: 'Percorso mirato al ritorno in campo dopo infortuni muscolari o articolari.',
    duration: '15-20 min',
    icon: 'Activity',
    steps: [
      {
        id: 'step1',
        type: 'choice',
        question: 'Qual è la zona principale dell\'infortunio?',
        options: [
          { label: 'Ginocchio', value: 'ginocchio' },
          { label: 'Caviglia', value: 'caviglia' },
          { label: 'Spalla', value: 'spalla' },
          { label: 'Altro', value: 'altro' },
        ],
      },
      {
        id: 'step2',
        type: 'pain',
        question: 'Indica il livello di dolore attuale a riposo:',
      },
      {
        id: 'step3',
        type: 'scale',
        question: 'Quanto ti senti fiducioso nel tornare all\'attività sportiva? (1-10)',
        min: 1,
        max: 10,
      },
      {
        id: 'step4',
        type: 'exercise',
        question: 'Test di stabilità monopodalica',
        exercise: {
          title: 'Equilibrio su una gamba',
          description: 'Rimani in equilibrio sulla gamba infortunata il più a lungo possibile.',
          duration: 30,
          illustrationUrl: 'https://picsum.photos/seed/balance/800/450',
          feedback: {
            low: 'Stabilità precaria, necessario lavoro propriocettivo.',
            medium: 'Buona stabilità, continua il rinforzo.',
            high: 'Ottima stabilità, pronto per carichi superiori.',
            thresholds: [15, 25],
          },
        },
      },
      {
        id: 'step5',
        type: 'choice',
        question: 'Senti instabilità durante il test?',
        options: [
          { label: 'Sì, molta', value: 'molta' },
          { label: 'Sì, leggera', value: 'leggera' },
          { label: 'No, stabile', value: 'no' },
        ],
      },
      // Logic-dependent steps
      {
        id: 'step6_ginocchio',
        type: 'exercise',
        question: 'Test mobilità ginocchio',
        condition: (answers) => answers.step1 === 'ginocchio',
        exercise: {
          title: 'Flessione ginocchio assistita',
          description: 'Esegui delle flessioni controllate del ginocchio.',
          duration: 45,
          targetReps: 15,
          illustrationUrl: 'https://picsum.photos/seed/knee/800/450',
          feedback: {
            low: 'Mobilità ridotta.',
            medium: 'Buona mobilità.',
            high: 'Ottima capacità funzionale.',
            thresholds: [8, 14],
          },
        },
      },
      {
        id: 'step6_spalla',
        type: 'exercise',
        question: 'Test mobilità spalla',
        condition: (answers) => answers.step1 === 'spalla',
        exercise: {
          title: 'Rotazione esterna',
          description: 'Esegui rotazioni esterne con il braccio a 90 gradi.',
          duration: 45,
          targetReps: 12,
          illustrationUrl: 'https://picsum.photos/seed/shoulder/800/450',
          feedback: {
            low: 'Range di movimento limitato.',
            medium: 'Mobilità nella norma.',
            high: 'Eccellente controllo motorio.',
            thresholds: [6, 10],
          },
        },
      },
      {
        id: 'step7',
        type: 'slider',
        question: 'Livello di gonfiore percepito (0-100%):',
        min: 0,
        max: 100,
      },
      {
        id: 'step8',
        type: 'text',
        question: 'Descrivi eventuali sensazioni anomale (scatti, blocchi, calore):',
      },
      {
        id: 'step9',
        type: 'exercise',
        question: 'Squat Test di controllo',
        exercise: {
          title: 'Squat controllati',
          description: 'Esegui quanti più squat possibili con tecnica corretta.',
          duration: 60,
          targetReps: 20,
          illustrationUrl: 'https://picsum.photos/seed/squat/800/450',
          feedback: {
            low: 'Forza e controllo da migliorare.',
            medium: 'Buona capacità funzionale.',
            high: 'Ottima performance atletica.',
            thresholds: [10, 20],
          },
        },
      },
      {
        id: 'step10',
        type: 'choice',
        question: 'Come valuti la sessione di oggi?',
        options: [
          { label: 'Troppo intensa', value: 'intensa' },
          { label: 'Adeguata', value: 'adeguata' },
          { label: 'Leggera', value: 'leggera' },
        ],
      },
    ],
  },
  {
    id: 'anziani',
    title: 'Programma movimento per anziani',
    description: 'Esercizi dolci per mantenere mobilità, equilibrio e autonomia.',
    duration: '20-25 min',
    icon: 'User',
    steps: [
      { id: 's1', type: 'choice', question: 'Come ti senti oggi?', options: [{label: 'Bene', value: 'bene'}, {label: 'Stanco', value: 'stanco'}] },
      { id: 's2', type: 'pain', question: 'Hai dolori particolari?' },
      { id: 's3', type: 'exercise', question: 'Sit-to-stand test', exercise: { title: 'Alzati e siediti', description: 'Alzati dalla sedia e risiediti.', duration: 30, illustrationUrl: 'https://picsum.photos/seed/sitstand/800/450', feedback: { low: 'Mobilità ridotta', medium: 'Buona', high: 'Ottima', thresholds: [5, 10] } } },
      { id: 's4', type: 'scale', question: 'Livello di fatica percepito', min: 1, max: 10 },
      { id: 's5', type: 'exercise', question: 'Marcia sul posto', exercise: { title: 'Marcia', description: 'Solleva le ginocchia alternandole.', duration: 60, illustrationUrl: 'https://picsum.photos/seed/march/800/450', feedback: { low: 'Ritmo lento', medium: 'Ritmo costante', high: 'Ottimo vigore', thresholds: [20, 40] } } },
      { id: 's6', type: 'choice', question: 'Hai avuto capogiri durante l\'esercizio?', options: [{label: 'Sì', value: 'si'}, {label: 'No', value: 'no'}] },
      { id: 's7', type: 'slider', question: 'Qualità del sonno recente', min: 0, max: 100 },
      { id: 's8', type: 'exercise', question: 'Equilibrio assistito', exercise: { title: 'Appoggio su un piede', description: 'Tieniti a uno schienale se necessario.', duration: 20, feedback: { low: 'Equilibrio da allenare', medium: 'Stabile', high: 'Molto stabile', thresholds: [5, 15] } } },
      { id: 's9', type: 'text', question: 'Note per il terapista:', },
      { id: 's10', type: 'choice', question: 'Vuoi continuare con questi esercizi?', options: [{label: 'Sì', value: 'si'}, {label: 'No', value: 'no'}] },
    ],
  },
  {
    id: 'posturale',
    title: 'Esercizio posturale',
    description: 'Correzione della postura e sollievo da tensioni muscolari croniche.',
    duration: '15 min',
    icon: 'Accessibility',
    steps: [
      { id: 'p1', type: 'choice', question: 'Dove senti più tensione?', options: [{label: 'Collo', value: 'collo'}, {label: 'Schiena alta', value: 'schiena_alta'}, {label: 'Lombare', value: 'lombare'}] },
      { id: 'p2', type: 'pain', question: 'Intensità della tensione:' },
      { id: 'p3', type: 'exercise', question: 'Circonduzioni spalle', exercise: { title: 'Spalle', description: 'Ruota le spalle all\'indietro.', duration: 30, illustrationUrl: 'https://picsum.photos/seed/shoulders/800/450', feedback: { low: 'Tensione alta', medium: 'Sciolto', high: 'Ottimo', thresholds: [10, 20] } } },
      { id: 'p4', type: 'text', question: 'Lavori molto al computer?', },
      { id: 'p5', type: 'exercise', question: 'Allungamento pettorali', exercise: { title: 'Apertura petto', description: 'Apri le braccia a croce.', duration: 45, illustrationUrl: 'https://picsum.photos/seed/chest/800/450', feedback: { low: 'Chiusura accentuata', medium: 'Buona apertura', high: 'Ottima elasticità', thresholds: [5, 10] } } },
      { id: 'p6', type: 'choice', question: 'Senti formicolii alle braccia?', options: [{label: 'Sì', value: 'si'}, {label: 'No', value: 'no'}] },
      { id: 'p7', type: 'scale', question: 'Livello di stress generale', min: 1, max: 10 },
      { id: 'p8', type: 'exercise', question: 'Gatto-Mucca (Mobilità colonna)', exercise: { title: 'Mobilità colonna', description: 'Inarca e fletti la schiena in quadrupedia.', duration: 60, illustrationUrl: 'https://picsum.photos/seed/catcow/800/450', feedback: { low: 'Rigidità', medium: 'Fluido', high: 'Ottima mobilità', thresholds: [8, 15] } } },
      { id: 'p9', type: 'slider', question: 'Quanto ti senti "dritto" ora?', min: 0, max: 100 },
      { id: 'p10', type: 'choice', question: 'Sessione utile?', options: [{label: 'Molto', value: 'molto'}, {label: 'Abbastanza', value: 'abbastanza'}] },
    ],
  },
  {
    id: 'mobilita',
    title: 'Valutazione mobilità e flessibilità',
    description: 'Screening completo dei range articolari principali.',
    duration: '10-15 min',
    icon: 'StretchHorizontal',
    steps: [
      { id: 'm1', type: 'choice', question: 'Sei uno sportivo praticante?', options: [{label: 'Sì', value: 'si'}, {label: 'No', value: 'no'}] },
      { id: 'm2', type: 'exercise', question: 'Touch toes test', exercise: { title: 'Flessione busto', description: 'Cerca di toccare le punte dei piedi.', duration: 30, illustrationUrl: 'https://picsum.photos/seed/toes/800/450', feedback: { low: 'Scarsa flessibilità', medium: 'Buona', high: 'Ottima', thresholds: [1, 2] } } },
      { id: 'm3', type: 'pain', question: 'Dolore durante la flessione?' },
      { id: 'm4', type: 'exercise', question: 'Deep Squat Mobility', exercise: { title: 'Accosciata profonda', description: 'Scendi in squat profondo talloni a terra.', duration: 45, illustrationUrl: 'https://picsum.photos/seed/deepsquat/800/450', feedback: { low: 'Rigidità caviglie/anche', medium: 'Buona', high: 'Ottima', thresholds: [5, 10] } } },
      { id: 'm5', type: 'scale', question: 'Flessibilità percepita', min: 1, max: 10 },
      { id: 'm6', type: 'exercise', question: 'Intra-rotazione anca', exercise: { title: 'Anca', description: 'Ruota l\'anca internamente da seduto.', duration: 30, illustrationUrl: 'https://picsum.photos/seed/hip/800/450', feedback: { low: 'Limitata', medium: 'Normale', high: 'Ottima', thresholds: [5, 12] } } },
      { id: 'm7', type: 'text', question: 'Precedenti interventi chirurgici?', },
      { id: 'm8', type: 'exercise', question: 'Neck mobility', exercise: { title: 'Collo', description: 'Ruota il collo a destra e sinistra.', duration: 30, illustrationUrl: 'https://picsum.photos/seed/neck/800/450', feedback: { low: 'Blocchi', medium: 'Libero', high: 'Molto fluido', thresholds: [10, 20] } } },
      { id: 'm9', type: 'slider', question: 'Idratazione giornaliera', min: 0, max: 100 },
      { id: 'm10', type: 'choice', question: 'Risultati soddisfacenti?', options: [{label: 'Sì', value: 'si'}, {label: 'No', value: 'no'}] },
    ],
  },
  {
    id: 'prevenzione',
    title: 'Prevenzione infortuni sportivi',
    description: 'Test di screening per identificare fattori di rischio.',
    duration: '20 min',
    icon: 'ShieldCheck',
    steps: [
      { id: 'pr1', type: 'choice', question: 'Sport principale?', options: [{label: 'Calcio', value: 'calcio'}, {label: 'Running', value: 'running'}, {label: 'Tennis', value: 'tennis'}, {label: 'Crossfit', value: 'crossfit'}] },
      { id: 'pr2', type: 'exercise', question: 'Single Leg Hop Test', exercise: { title: 'Salto monopodalico', description: 'Salta in avanti su una gamba sola.', duration: 30, illustrationUrl: 'https://picsum.photos/seed/hop/800/450', feedback: { low: 'Instabilità', medium: 'Buon controllo', high: 'Ottima potenza', thresholds: [5, 10] } } },
      { id: 'pr3', type: 'pain', question: 'Dolore all\'atterraggio?' },
      { id: 'pr4', type: 'exercise', question: 'Plank Test', exercise: { title: 'Plank', description: 'Mantieni la posizione di plank.', duration: 60, illustrationUrl: 'https://picsum.photos/seed/plank/800/450', feedback: { low: 'Core debole', medium: 'Stabile', high: 'Core forte', thresholds: [30, 50] } } },
      { id: 'pr5', type: 'scale', question: 'Livello di stanchezza oggi', min: 1, max: 10 },
      { id: 'pr6', type: 'exercise', question: 'Affondi alternati', exercise: { title: 'Affondi', description: 'Esegui affondi mantenendo il busto dritto.', duration: 45, illustrationUrl: 'https://picsum.photos/seed/lunges/800/450', feedback: { low: 'Squilibrio', medium: 'Buono', high: 'Ottimo', thresholds: [10, 20] } } },
      { id: 'pr7', type: 'text', question: 'Ore di sonno medie?', },
      { id: 'pr8', type: 'exercise', question: 'Y-Balance Test (Semplificato)', exercise: { title: 'Equilibrio dinamico', description: 'Allunga la gamba libera in 3 direzioni.', duration: 60, illustrationUrl: 'https://picsum.photos/seed/ybalance/800/450', feedback: { low: 'Rischio infortunio alto', medium: 'Medio', high: 'Basso', thresholds: [6, 12] } } },
      { id: 'pr9', type: 'slider', question: 'Carico di allenamento settimanale', min: 0, max: 100 },
      { id: 'pr10', type: 'choice', question: 'Ti senti pronto per la gara?', options: [{label: 'Sì', value: 'si'}, {label: 'No', value: 'no'}] },
    ],
  },
];
